### ISSUE TITLE
style is gone in GitHub

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay-everywhere#34] opened 2014-10-17 15:03 UTC
![screen shot 2014-10-17 at 11 03 16 am](https://cloud.githubusercontent.com/assets/134455/4680925/cad579aa-560e-11e4-8bcc-44e6257a1870.png)

**Comment by rohitpaulk** [comment] 2015-03-20 16:29
Oops, here's how it looks now: 

![screenshot from 2015-03-20 21 58 14](https://cloud.githubusercontent.com/assets/3893573/6755906/4bbcb040-cf4c-11e4-8d74-0c82ed4e1dfb.png)

I've checked my console for errors - none.

**Comment by kzisme** [comment] 2015-07-07 13:00
![gratieverywhere](https://cloud.githubusercontent.com/assets/3493562/8546465/110c7f4a-2486-11e5-8f46-245915a3e2a1.PNG)

Current state of the button on Github - currently reading into some possible fixes.  Using the !important tag might be a possible easy fix - currently looking into that option.  

Also are there any other websites where we would want to place a Gratipay button? 

Lastly,  I'm trying to figure out a simple way to test/debug chrome extensions.

**Comment by kzisme** [comment] 2015-07-07 13:35
Currently wondering if the style is also broken on Bitbucket/Twitter.  I'm still trying to find a decent way to look into the debugging of extensions - since I'm not finding much aside from Chrome Dev Tools - (which I've already been using)

**Comment by kzisme** [comment] 2015-07-07 13:43
I currently don't see (or I'm just over-looking it) the gratipay button (or icon) within BitBucket or Twitter either.  Still poking around though...

**Comment by kzisme** [comment] 2015-07-07 16:56
Alright so it appears that using the !important tag is a ~last resort~ sort of deal.  

So the issue is with CSS Specificity (I think)

What's happening is the id selector for the BitBucket button is taking precedence over the Github selector.

The specificity hierarchy from what I understand is as follows:

ID > Class > Element

The only issue I'm running into now is...is there a way to change the selector type without messing up a lot of things, or do we even need the BitBucket information in there currently.  

The only difference between the two methods(?) is the size of the button, so I'm curious if they are needed.

Going to look into #29 now until I get some input

**Comment by clone1018** [comment] 2015-07-07 17:00
We should only be loading bitbucket css on bitbucket and GitHub css on GitHub, we use the important to enforce our styles on a website we don't control. It's probably broken because GitHub changed their root styles.

**Comment by kzisme** [comment] 2015-07-07 17:04
@clone1018 So, we just need to change it to match their new root styles, or how would that work?

(sorry I'm new to chrome extensions and such)

**Comment by clone1018** [comment] 2015-07-07 17:11
It's pretty simple, we're allowed to run custom js and css on the GitHub website via it, we add HTML here to look like a GitHub button https://github.com/gratipay/gratipay-everywhere/blob/master/chrome/websites/github/github.js#L22 (their default style) and then customize it here: https://github.com/gratipay/gratipay-everywhere/blob/master/chrome/button/button.css#L2

**Comment by kzisme** [comment] 2015-07-07 17:15
So, on the initial link (their Github Buttons) changed? - and that's why it broke?

**Comment by clone1018** [comment] 2015-07-07 18:37
Sorry I meant to link this line: https://github.com/gratipay/gratipay-everywhere/blob/master/chrome/websites/github/github.js#L19 

It looks like they changed the class to: btn btn-sm

**Comment by kzisme** [comment] 2015-07-07 18:40
@clone1018 Wow....I was looking in Google Dev Tools this morning and was literally staring at their styling name btn....

Also is there a simple way for me to test if the proposed changes would work while building a Chrome Extension?

**Comment by clone1018** [comment] 2015-07-07 19:02
All you have to do is zip the chrome folder and "Load Unpacked Extension" on chrome://extensions/ and select the zip.

**Comment by kzisme** [comment] 2015-07-07 19:13
Awesome!  I'll check it out and see what I come up with thanks for the guidance @clone1018 :+1:

**Comment by rohitpaulk** [comment] 2015-07-07 19:18
!m @kzisme

**Comment by kzisme** [comment] 2015-07-08 04:20
Alright I tested and committed the changes to fix this issue.  

@clone1018 was exactly right (thanks for the help)

I'll take a look at the next issue tomorrow :)

Current status:
![capture](https://cloud.githubusercontent.com/assets/3493562/8562987/2b991202-2507-11e5-840a-33d557e4e056.PNG)

!m @clone1018

**Comment by clone1018** [comment] 2015-07-08 14:18
@kzisme Do you want me to release it?

**Comment by kzisme** [comment] 2015-07-08 14:22
If you would like to - I feel like it would be a good idea since it fixes that functionality.  Although - I don't know how important/difficult it is to push changes to a chrome extension.

**Comment by whit537** [comment] 2015-07-09 16:49
Yay team! :dancer: 

!m @kzisme @clone1018 

Reopening until we've deployed the fix. I'm still seeing 0.13 (November 18, 2014) at https://chrome.google.com/webstore/detail/gratipay-everywhere/ffbkkncpfcobpjaolefljnpmianmflig.

**Comment by clone1018** [comment] 2015-07-09 18:57
Good because I forgot :D! "Your item is in the process of being published and may take up to 60 minutes to appear in the Chrome Web Store. "

**Comment by kzisme** [comment] 2015-07-09 19:06
@clone1018 @whit537 Just checked and it seems as though it has been updated in the Chrome Webstore :) I'm going to close this issue, but feel free to reopen/comment as needed.

**Closed by kzisme** 2015-07-09 19:06 UTC

**Comment by chadwhitacre** [comment] 2015-07-09 23:14
Huzzah! :dancer: 

![screen shot 2015-07-09 at 7 14 03 pm](https://cloud.githubusercontent.com/assets/134455/8609015/c6675bb4-266e-11e5-9c37-f731e1a4e2cb.png)

**Comment by chadwhitacre** [comment] 2015-07-09 23:21
@kzisme Looks like you committed directly to master in https://github.com/gratipay/gratipay-everywhere/commit/1efcc21aef9c2465aa0a6d6380ea27f7dcb56368, ya? Let's observe our usual [pull request workflow](http://inside.gratipay.com/howto/build-gratipay) for code changes (note that changes to markdown docs can go directly on master).

**Comment by chadwhitacre** [comment] 2015-07-09 23:22
Sorry, here's the right link: http://inside.gratipay.com/howto/build-gratipay. :-)

**Comment by kzisme** [comment] 2015-07-10 14:26
@whit537 I thought I committed to the css-data-uri branch.  Is there a simple way to check based on my commit?

When I view [this](https://github.com/gratipay/gratipay-everywhere/blob/1efcc21aef9c2465aa0a6d6380ea27f7dcb56368/chrome/websites/github/github.js)

At the top when I select "Tree" it doesn't have the master branch selected.  I just did a quick edit in browser (since it was a small change) and I tested it locally.  

Next time (as per the docs) 

> use a topic branch in the main repo

Is that right?  

Sorry, still getting used to everything :)

**Comment by chadwhitacre** [comment] 2015-07-11 01:36
> Is there a simple way to check based on my commit?

I do see an indicator in the GitHub UI for https://github.com/gratipay/gratipay-everywhere/commit/1efcc21aef9c2465aa0a6d6380ea27f7dcb56368:

![screen shot 2015-07-10 at 9 31 49 pm](https://cloud.githubusercontent.com/assets/134455/8631672/2642d91e-274b-11e5-866b-d6625403b113.png)

> At the top when I select "Tree" it doesn't have the master branch selected.

That's because, per the URL, you're browsing the tree at commit 1efcc21aef9c2465aa0a6d6380ea27f7dcb56368. Branches in Git are light-weight pointers to SHA-1 hashes. As you add commits to the `master` branch you are really adding a commit (changeset, diff) to Git history and updating the `master` branch/pointer to point to your new commit via it's SHA-1 hash. Note that `css-data-uri` is not selected either.

> Is that right?

Yup! :-)

> Sorry, still getting used to everything :)

!m @kzisme 

Want to schedule a Google Hangout for Monday at 11am to go over PR workflow together?

**Comment by kzisme** [comment] 2015-07-13 12:07
@whit537 I will be unable to do a call, but I will be available to chat via hangouts.  Would that work for you?

**Comment by chadwhitacre** [comment] 2015-07-13 12:16
@kzisme Sure thing. 11am still good?

**Comment by kzisme** [comment] 2015-07-13 12:26
Yup, works for me!

**Comment by kzisme** [comment] 2015-07-13 14:57
@whit537 Ready when you are
